### ISSUE TITLE
sms plugin not compatible with map_view 

### ISSUE THREAD

**Issue by nitneuq33** [babariviere/flutter_sms#11]
hello when I install  sms: "^0.0.9" with  map_view: "^0.0.12" I have this issue. 

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  map_view: "^0.0.12"
  sms: "^0.0.9"

-------------------------------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-v4' has different version for the compile (25.2.0) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle build failed: 1

---------------------------------------------------------------------------------------

C:\flutter\bin\flutter.bat --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [version 10.0.16299.309], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] VS Code, 64-bit edition (version 1.21.1)
[√] Connected devices (1 available)

• No issues found!
Process finished with exit code 0

**Comment by babariviere** [comment]
Hi,

I have pushed a new version, can you test it?

**Comment by nitneuq33** [comment]
yes it's ok :) thank you
