### ISSUE TITLE
how to listen and read a futur sms

### ISSUE THREAD

**Issue by nitneuq33000** [babariviere/flutter_sms#13]
hello, Actually when I send me an SMS I can print only the previous sms and not wait to receive the sms ( in transistion ) and print it when it's receive. how can I do that.

**Comment by nitneuq33000** [comment]
Okay, it's very important feature for my app, waiting for that :) good
luck, and thanks for your job.

2018-04-23 12:17 GMT+02:00 Bastien Rivière <notifications@github.com>:

**Comment by babariviere** [comment]
@nitneuq33000 We have implemented the feature, you can test it like that:

```dart
  SmsSender sender = new SmsSender();
  String address = getAddress();
  ...
  SmsMessage message = new SmsMessage(address, 'Hello flutter!');
  message.addStateListener((state) {
  if (state == SmsMessageState.Sent) {
    print("SMS is sent!");
  } else if (state == SmsMessageState.Delivered) {
    print("SMS is delivered!");
  }
});
sender.sendSms(message);
```

**Comment by nitneuq33** [comment]
@babariviere I tried, I upload pubspec.yaml

I have an error with getAdress () (no defined methode  ) so I change the code like this

  SmsSender sender = new SmsSender();
  ...
  SmsMessage message = new SmsMessage(+33---------, 'Hello flutter!');
  message.addStateListener((state) {
  if (state == SmsMessageState.Sent) {
    print("SMS is sent!");
  } else if (state == SmsMessageState.Delivered) {
    print("SMS is delivered!");
  }
});
sender.sendSms(message);

I have this error message:

compiler message: lib/SecondPage.dart:181:38: Error: Getter not found: 'SmsMessageState'.
compiler message:                         if (state == SmsMessageState.Sent) {
compiler message:                                      ^^^^^^^^^^^^^^^
compiler message: lib/SecondPage.dart:183:45: Error: Getter not found: 'SmsMessageState'.
compiler message:                         } else if (state == SmsMessageState.Delivered) {
compiler message:                                             ^^^^^^^^^^^^^^^
compiler message: lib/SecondPage.dart:180:31: Error: The method 'addStateListener' isn't defined for the class 'sms::SmsMessage'.
compiler message: Try correcting the name to the name of an existing method, or defining a method named 'addStateListener'.
compiler message:                       message.addStateListener((state) {
compiler message:                               ^
compiler message: lib/SecondPage.dart:181:38: Error: The getter 'SmsMessageState' isn't defined for the class '#lib1::_MyAppState'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'SmsMessageState'.
compiler message:                         if (state == SmsMessageState.Sent) {
compiler message:                                      ^
compiler message: lib/SecondPage.dart:183:45: Error: The getter 'SmsMessageState' isn't defined for the class '#lib1::_MyAppState'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'SmsMessageState'.
compiler message:                         } else if (state == SmsMessageState.Delivered) {
compiler message:

**Comment by babariviere** [comment]
It's a string so you have to put it between "

**Comment by nitneuq33** [comment]
sorry I'm a noob ^^ I tried to put my number +336-------  everywhere 

 String address = getAddress();
 String address = getAddress();
 String address = getAddress();

**Comment by nitneuq33** [comment]
Yes absolutly

**Comment by babariviere** [comment]
You can use message.body 😃
