### ISSUE TITLE
logo design contribution

### ISSUE THREAD

**Issue by saifulfrank** [babariviere/flutter_sms#16]
Hi
I want to make a logo for this projects if you have any requirements then let me know.its totally free for open source projects.

**Comment by joanpablo** [comment]
I think it's a great idea, thanks very much, for me your contribution is very welcome.  What do you think about that @babariviere ?

**Comment by babariviere** [comment]
Yes! You can do as you want. Thanks you in advance!

**Comment by saifulfrank** [comment]
I have created three logos for you. As its name started with the letter "F" so I have tried to reflect "F" on them. which one of your choices tell me that I'll give you that source file. If you think something needs to be changed then you can tell me I'll change.

![fluttssms](https://user-images.githubusercontent.com/37498811/40992740-6f2e9ae2-6919-11e8-8abe-e3b52a5ddaf3.png)
![fluttssms1](https://user-images.githubusercontent.com/37498811/40992741-709f2a22-6919-11e8-9777-0ca2144926e0.png)
![fluttssms3](https://user-images.githubusercontent.com/37498811/40992742-71d8c13c-6919-11e8-9f73-324565ce1336.png)

**Comment by babariviere** [comment]
I think I prefer the first one ! Really good work! You can create a pull request to add it on the Readme if you want 😁

**Comment by joanpablo** [comment]
Thanks a lot Imrul for contribute, I think that a product to become a
success one, must have 3 thinks: 1- Be a valuable product of course,  2- It
must have a good documentation, 3- and it must have a good Logo, hehehehe,
so thanks for helping us with that. Now my considerations: The first and
the seconds are the ones I like must.

I expect to have a logo that in some way combines the styles of a SMS
concept (something related with that) and the Flutter framework (maybe the
colors of the flutter logo, the shape of flutter logo, etc) so the logo
must capture in some way, the essence of sms and the flutter logo.

The first one have the essence of SMS but not of Flutter. And the second
one capture a little the escence of the Flutter logo in shapes but it's to
sharped. And also I don't feel confortable with the colors yet. What do you
think about trying some material's style colors? just a suggestion.

This is just my opinion, I think you are doing a great work and again
thanks a lot for helping us and contribute with it.

**Comment by saifulfrank** [comment]
I have updated 2nd logo with updated color that matches the flutter logo. And changed color of the first logo. Let me know your opinion. 
Thank you
![fluttssms4](https://user-images.githubusercontent.com/37498811/41017092-267bde5c-6975-11e8-983c-852246bba53d.png)
![fluttssmss](https://user-images.githubusercontent.com/37498811/41017093-26c49d40-6975-11e8-8843-61da6d7f5b0c.png)

**Comment by saifulfrank** [comment]
if need any changes then let me know.

**Comment by joanpablo** [comment]
Great work,  thanks, but what do think about removing the gradients and use just solid colors? I prefers solid colors, it's just and idea. Excuse me if I'm rigorous, hehehe I think you'r doing a great work.

**Comment by saifulfrank** [comment]
Happy to know that 😊
its ok. A designer should have patience on his work to satisfy others. 😊
which one you choose for the project let me know. then I will remove gradient and will give you source files with other necessary files. let me know
Thanks to you both

**Comment by joanpablo** [comment]
I would like to test both logos without gradients, and see which one looks better.

**Comment by saifulfrank** [comment]
please check pull #17

**Comment by joanpablo** [comment]
I prefer Logo1
https://drive.google.com/drive/folders/14qCwvvqNQVcjyBMslogYMVz4kyuONWfG

**Comment by saifulfrank** [comment]
great! I have updated pull request, please check #17
