### ISSUE TITLE
toString is not getting called on error objects present in print statement

### ISSUE THREAD

**Issue by sankarcheppali** [babariviere/flutter_sms#24]
Hi,

Getting following exception when trying to send message on android

E/flutter (27267): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (27267): type 'PlatformException' is not a subtype of type 'String'
E/flutter (27267): #0      new SmsSender._private.<anonymous closure> (package:sms/sms.dart:311:71)
E/flutter (27267): #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
E/flutter (27267): #2      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
E/flutter (27267): #3      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16)
E/flutter (27267): #4      _DelayedError.perform (dart:async/stream_impl.dart:595:14)
E/flutter (27267): #5      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
E/flutter (27267): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
E/flutter (27267): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (27267): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

SMS package version : 0.2.0

environment details 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2018.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected devices (3 available)

! Doctor found issues in 1 category.

**Comment by babariviere** [comment]
Yes sorry for the issue, I will take a look tomorrow

**Comment by babariviere** [comment]
Can you tell me what happened for getting this error?
