### ISSUE TITLE
Update for Dart 2.

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [babariviere/flutter_sms#26]
>Support Dart 2 in pubspec.yaml.

>The SDK constraint in pubspec.yaml doesn't allow the Dart 2.0.0 release. For information about >upgrading it to be Dart 2 compatible, please see https://www.dartlang.org/dart-2#migration.
<img width="730" alt="screen shot 2018-09-04 at 6 38 04 pm" src="https://user-images.githubusercontent.com/23037821/45066129-b3416300-b071-11e8-82fe-ef4885aca681.png">

**Comment by babariviere** [comment]
Should be fixed with the new version
