### ISSUE TITLE
Need update the plugin to dart sdk 2.1 

### ISSUE THREAD

**Issue by nitneuq33000** [babariviere/flutter_sms#39]
I have upgrade dart sdk to 2.1.0 and now the plugin isn't working.

**Comment by babariviere** [comment]
Can you give some more information?

**Comment by nitneuq33000** [comment]
I desinstall flutter folder and reinstall flutter, reupload dart SDK. Now
dart is 2.1.0 and when I want use the " flutter packages get" to upload
packages I have this error :

$ flutter packages get
Running "flutter packages get" in test3...
The current Dart SDK version is 2.1.0-dev.5.0.flutter-a2eb050044.

Because test3 depends on sms >=0.0.2 <0.2.2 which requires SDK version
>=1.0.0 <2.0.0, version solving failed.

pub get failed (1)


I have this error for all my packages not only sms...

Le sam. 20 oct. 2018 à 12:00, Bastien Rivière <notifications@github.com> a
écrit :

**Comment by nitneuq33000** [comment]
here is my pubspec yaml

dependencies:
  flutter:
    sdk: flutter
  sms: "^0.1.4"

**Comment by nitneuq33000** [comment]
Sorry problem solved. I didn't use the lasted version ... T_T

**Comment by babariviere** [comment]
No problem haha
