### ISSUE TITLE
Write documentation about the main functionalities of the package

### ISSUE THREAD

**Issue by joanpablo** [babariviere/flutter_sms#5]
I think it's time for writing some documentation about the main functionalities of the package, and add it to the README.md file. I will start with it now.

**Comment by babariviere** [comment]
Yup, we should do it for 0.1.0 release

**Comment by joanpablo** [comment]
I have updated the docs, and uploaded a more complete example app with almost all functionalies of package

**Comment by babariviere** [comment]
This is way more cleaner now!
