### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by babariviere** [babariviere/flutter_sms#7]
Add all features to the example app.

**Comment by joanpablo** [comment]
I think that develop a simple but fully functional sms messages app it's a good idea for showing all the features of the package. I have been developing a simple one app for testing the functionalities. I think it may be useful.

**Comment by babariviere** [comment]
Yup that's a good idea

**Comment by joanpablo** [comment]
Sample app updated, let me know your opinion about it.

**Comment by babariviere** [comment]
Perfect! We can close this issue :yum:
