### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by babariviere** [babariviere/flutter_sms#8]
When we are trying to request more than one request, we got an error and permission request is skipped

**Comment by joanpablo** [comment]
In Android applications (API version> 23) you can not request more than one set of permissions at a time, you can request one or more permissions, but only in the same request. In a 'Flutter' application when you have multiple 'Channels' to communicate with the platform code, and those 'Channels' request different sets of permissions, they will request everything at the same time, and that's when the error is thrown.

We have two options to handle it:

1- When the 'flutter_sms' package is loaded for the first time, we could request all the permissions that we will need, even if not all the functionalities of the package are required, or:

2- Putting in a queue all the permission requests and execute them one by one as they are required.

My approach was the second one. Now the app doesn't crash when requesting permissions to the user.
